language: python
sudo: false
python:
    - 2.7
    - pypy-5.4.1
    - 3.4
    - 3.5
    - 3.6
install:
    - pip install -U pip setuptools
    - pip install -U coverage coveralls
    # workaround https://github.com/zopefoundation/BTrees/issues/70
    - pip install -U --no-binary ":all:" persistent
    - pip install -e  git+https://github.com/zopefoundation/zope.proxy.git#egg=zope.proxy
    - pip install -U -e .[test]
script:
  - coverage run -m zope.testrunner --test-path=src  --auto-color --auto-progress
notifications:
    email: false
after_success:
    - coveralls
cache: pip
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
